export const metadata = {
    title: "Auth page",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}) {
    return (
        <div className="h-full flex justify-center items-center">
            {children}
        </div>
    );
}